### ISSUE TITLE
dslink/wifiboot incompatibility on DSi hardware

### ISSUE THREAD

**Issue by dmorgan81** [devkitPro/dslink#2]
When running wifiboot on actual DSi hardware and sending a file over with dslink host the almost every file boots to a white screen. The only file I've found that does boot is nocash's magicflr: https://problemkaputt.de/magicflr.htm

All the devkitpro examples will not boot when pushed with dslink host to wifiboot.

Scouring the web turned up a mention of the same problem in this thread: https://devkitpro.org/viewtopic.php?f=38&t=8628

I'm not sure if this is an issue with dslink host or wifiboot (or something else), but since contacting nocash doesn't appear to be possible and the linked forum post above requested samples of nonbooting files I figured I'd open an issue here.

**Comment by WinterMute** [comment]
wifiboot and dslink are not compatible because Martin has zero concept of being able to work with anyone else or any concept of maintaining compatibilty. I'm not even sure if wifiboot is compatible with any of our code since Martin is pretty much a law unto himself. Sorry for the inconvenience.

dslink was originally written to allow transfer of binaries to a DSi with no other means of booting code and is, unfortunately, currently limited to wep until we find some time to bring up proper homebrew support for DSi wifi. If you're prepared to put up with that in the meantime then the [FlipNote ( ͡° ͜ʖ ͡°)](https://davejmurphy.com/%cd%a1-%cd%9c%ca%96-%cd%a1/) archive contains a recent hbmenu build and ds side dslink binary which were working last time I checked.

I don't really expect that we can resolve incompatibilty with Martin, sorry.
